Repository cre-ne-jp/rgrb, pull requests merged in 2019-07, with the labels that each got.

#129 library-verUP-201907: bundle update
  Gemfile.lock
Labels: dependencies

#131 IRCボット：シグナル受信で正常に終了しない問題を修正する
  lib/rgrb/exec/irc_bot.rb
Labels: bug

#139 Secret dice mkdir p
  lib/rgrb/plugin/dice_roll/generator.rb
  spec/rgrb/plugin/dice_roll/data/.keep
  spec/rgrb/plugin/dice_roll/generator_spec.rb
Labels: enhancement

#140 secret_dice: シークレットロールのテストを追加する
  spec/rgrb/plugin/dice_roll/generator_spec.rb
Labels: enhancement

#141 DiceRoll: テスト「出目に偏りがない」で失敗する確率を減らす
  spec/rgrb/plugin/dice_roll/generator_spec.rb
Labels: enhancement

#160 ランダムジェネレータ：テストで必要なメソッドをpublicにする
  lib/rgrb/plugin/random_generator/generator.rb
  spec/rgrb/plugin/random_generator/generator_spec.rb
  spec/rgrb/plugin/server_connection_report/mail_generator_spec.rb
Labels: enhancement

#162 BCDice: コンストラクタでBCDiceを用意する
  lib/rgrb/plugin/bcdice/generator.rb
  spec/rgrb/plugin/bcdice/generator_spec.rb
Labels: enhancement

#161 Bcdice: テストに失敗するようになったのを修正
  lib/rgrb/plugin/bcdice/discord_adapter.rb
  lib/rgrb/plugin/bcdice/generator.rb
  lib/rgrb/plugin/bcdice/irc_adapter.rb
  spec/rgrb/plugin/bcdice/generator_spec.rb
Labels: bug
